# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licenseplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=20, verbose_name='车牌')),
            ],
            options={
                'db_table': 'license_info',
            },
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggest', models.CharField(max_length=200, verbose_name='建议')),
            ],
            options={
                'db_table': 'feed_info',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='用户名')),
                ('openid', models.CharField(max_length=100, verbose_name='openid')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('isStop', models.CharField(default=False, max_length=5)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='钱包')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.AddField(
            model_name='suggestions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.UserProfile'),
        ),
        migrations.AddField(
            model_name='licenseplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.UserProfile'),
        ),
    ]
