# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-20 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licenseplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=20, verbose_name='车牌')),
            ],
            options={
                'db_table': 'license_info',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('nickname', models.CharField(max_length=50, verbose_name='用户名')),
                ('openid', models.CharField(max_length=100, verbose_name='openid')),
                ('email', models.EmailField(max_length=254)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.AddField(
            model_name='licenseplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.UserProfile'),
        ),
    ]
