# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-18 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=None, max_length=50, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usercount',
            field=models.CharField(default=None, max_length=50, verbose_name='用户账号'),
        ),
    ]
