# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-18 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0002_auto_20200518_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='openid',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='openid'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='usercount',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='用户账号'),
        ),
    ]
