# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-29 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0002_auto_20200225_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggest', models.CharField(max_length=200, verbose_name='建议')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.UserProfile')),
            ],
            options={
                'db_table': 'feed_info',
            },
        ),
    ]
