# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
            options={
                'db_table': 'admin_profile',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('in_date', models.DateTimeField(auto_now_add=True)),
                ('out_date', models.DateTimeField(null=True)),
                ('stay_date', models.CharField(max_length=100, null=True)),
                ('car_type', models.CharField(max_length=20)),
                ('enter_info', models.CharField(max_length=20)),
                ('exit_info', models.CharField(max_length=20, null=True)),
                ('money', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('isout', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'park_car_info',
            },
        ),
        migrations.CreateModel(
            name='CS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('six_money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('after_money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('able', models.IntegerField()),
            ],
            options={
                'db_table': 'charge_standard',
            },
        ),
        migrations.CreateModel(
            name='NumberCar',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='车位数')),
            ],
            options={
                'db_table': 'Parking_digits',
            },
        ),
    ]
