# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-19 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='isout',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
