# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-21 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200220_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='CS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('six_money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('after_money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('able', models.IntegerField()),
            ],
            options={
                'db_table': 'charge_standard',
            },
        ),
    ]
