# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-02 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_cs'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='money',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
