# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-18 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200419_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': '管理员信息', 'verbose_name_plural': '管理员信息'},
        ),
        migrations.AlterModelOptions(
            name='numbercar',
            options={'verbose_name': '停车场车位', 'verbose_name_plural': '停车场车位'},
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='stateflag',
            field=models.IntegerField(default=0, verbose_name='修改状态'),
        ),
    ]
