# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-03 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_car_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='stay_date',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
