# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-03 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200303_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='stay_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
