# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-03 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200303_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='isout',
            field=models.IntegerField(default=0),
        ),
    ]
